trigger:
  branches:
    include:
      - master

pool:
  name: Default

steps:
  - checkout: self  # Faz o checkout do repositório

  # Instalar dependências npm
  - script: npm install
    displayName: 'Instalar dependências npm'

  # Instalar o Snyk e autenticar
  - script: |
      npm install -g snyk
      snyk auth $(SNYK_TOKEN)
    displayName: 'Instalar Snyk e autenticar'

  # Rodar o Snyk Test (verificar vulnerabilidades)
  - script: snyk test --all-projects --json-file-output=results.json
    displayName: 'Rodar Snyk Test'

  # Gerar o relatório HTML do Snyk Test
  - script: snyk-to-html -o $(Build.ArtifactStagingDirectory)/results-test.html < results.json
    displayName: 'Gerar relatório Snyk Test'

  # Rodar o Snyk Monitor (enviar para monitoramento contínuo)
  - script: snyk monitor --all-projects
    displayName: 'Rodar Snyk Monitor'

  # Publicar o relatório HTML como artefato
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: 'Snyk Reports'
    displayName: 'Publicar artefato de relatório'