pool:
  name: Default

steps:
  - checkout: self

  # install & prepare snyk
  - script: |
      npm i -g snyk
      snyk auth $(SNYK_TOKEN)
    displayName: 'snyk auth'

  # snyk code
  - script: snyk code test --org=nova8-cybersecurity-nfr-default
    continueOnError: true
    displayName: 'snyk code'

  # snyk open source
  - script: |
      echo "Iniciando instalação das dependências"
      npm install -g snyk
      snyk --version
      snyk test --org=nova8-cybersecurity-nfr-default
    continueOnError: true
    displayName: 'snyk test'
  
  # snyk monitor
  - script: |
      echo "Iniciando instalação das dependências"
      npm install -g snyk
      snyk --version
      snyk monitor --org=nova8-cybersecurity-nfr-default
    continueOnError: true
    displayName: 'snyk monitor'