pool:
  name: Default

steps:
  - checkout: self

  # install & prepare snyk
  - script: |
      npm install --location=global snyk
      snyk config set endpoint=https://api.us.snyk.io
      snyk auth $(SNYK_TOKEN)
    displayName: 'snyk auth'

  # snyk code
  - script: snyk code test --org=nova8-cybersecurity-nfr-default
    continueOnError: true
    displayName: 'snyk code'

  # snyk open source
  - script: snyk test --all-projects --org=nova8-cybersecurity-nfr-default
    continueOnError: true
    displayName: 'snyk test'
  
  # snyk monitor
  - script: snyk monitor --all-projects --org=nova8-cybersecurity-nfr-default
    continueOnError: true
    displayName: 'snyk monitor'