trigger:
  branches:
    include:
      - master

pool:
  name: Default

stages:
  - stage: SecurityScan
    displayName: 'Checkmarx AST Scan'
    jobs:
      - job: RunCheckmarxScan
        displayName: 'Executar Checkmarx AST'
        steps:
          - checkout: self

          - task: Checkmarx AST@3
            displayName: 'Executar análise com Checkmarx AST'
            inputs:
              CheckmarxService: 'Checkmarx'
              projectName: 'juice-shop'
              branchName: 'master'
              tenantName: 'natura'